project:
  type: website

website:
  title: "Yicheng Shen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research & Publications
      - href: teaching.qmd
        text: Teaching
    right:
      - icon: github
        href: https://github.com/sheny2
      - icon: linkedin
        href: https://www.linkedin.com/in/yicheng-shen

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true