---
title: "Research & Publications"
---

## Methodological Interests

My work bridges causal inference, Bayesian hierarchical modeling, and privacy-preserving federated learning, particularly focusing on how to handle realistic incomplete data and longitudinal EHR data across multi-institutional cohorts.

------------------------------------------------------------------------

## Working Papers & Preprints

-   **Shen, Y.**, Kim, J., Luo, C., Zeger, S. L., Shah, A. A., Tong, J. (2026). *MV-PEAL: A Federated Learning Framework for Multivariate Longitudinal EHR Data.* \[Submitted for the Annals of Applied Statistics\]
    -   **Winner of the 2026 ICSA Student Paper Award**
-   **Shen, Y.**, Kim, J., Luo, C., Zeger, S., Domsic, R. Shah, A., Tong, J. (2026). *Unlocking Multi-Institutional Insights into Disease Progression with Federated Learning: PEAL as a Lossless, One-Shot Solution.* \[In press at npj Digital Medicine\]
    -   **2026 AI Research Day Student Award**
-   Vazquez, J., **Shen, Y.**, Sanderson, K., Akulian, J., Tong, J., Stuart, E. A.(2026). *Federated Learning with Incomplete Data: A Weighted Approach.* \[Submitted for Biostatistics\]
-   Wu, X., **Shen, Y.**, Shan, M., Stuart, E., Lipkovich, I. (2026). *Comparing Federated Learning Methods for Estimating Average Treatment Effects in a Target Population from Multiple Real-world Studies and Randomized Trials.* \[Manuscript in preparation for Statistics in Medicine\]
-   Chao, A., **Shen, Y.**, Ghanta, A., Silver, N., Milardo, R., Santos, C., Tong, J. (2025). *Sex Differences in Response to Incretin-Based Medications for Obesity: Systematic Review and Meta-Analysis.* \[Invited Revision at Obesity Reviews\]
-   **Shen, Y.**, Chu, H., Hong, H. (2026). *Simulation-Based Methods for Power Calculation in Bayesian Network Meta-Analysis.* \[Invited revision at Journal of the Royal Statistical Society Series C\]
    -   **Honorable Mention for the BEST Award for Master's Research** (2024)

## Publications

-   **Shen, Y.**, Bail, C., & Volfovsky, A. (2026). *Enhancing joint ideal point estimation strategies with Twitter social networks and text data.* Network Science, 14, e10. doi: https://doi.org/10.1017/nws.2026.10028
-   **Shen, Y.** (2022). *Be Steady and Popular: a Modern Counter-Insurgency ABM.* NetLogo Modeling Commons.
-   **Shen, Y.** (2022). *Justified Cause? Assessing the Humanitarian Outcomes of US Foreign Aid and Intervention Since the Cold War.* PoliS: Carleton Journal of Political Science, inaugural edition, pp.129-167.
    -   **Distinction on Senior Thesis - Political Science** (2022)
-   **Shen, Y.**, Flignor, J., Nachreiner, L., & Wang, K. (2022). *Behind the Smoke: An Extreme Value Analysis of Air Pollution in Minnesota.* Consortium for the Advancement of Undergraduate Statistics Education, spring 2022 issue.
    -   **First Prize in Undergraduate Statistics Research Project Competition** (2022)
    -   **Distinction on Senior Thesis - Statistics** (2022)

## Book Chapters

-   Knoke, D. (2025). *Insurging.* In Network Collective Action: Agent-Based Models of Pandemics, Riots, Social Movements, Insurrections and Insurgencies (pp. 89-100). Cham: Springer Nature Switzerland. (Coauthored Chapter)

## Invited Conferences & Presentations

**2026**

-   Joint Statistical Meeting (JSM)
-   ICSA Applied Statistics Symposium *(Recipient of the NSF Travel Award)*
-   Johns Hopkins inHealth Precision Medicine Symposium
-   PHAISE AI Research Day
-   Duke Industry Statistics Symposium (DISS)
-   Eastern North American Region (ENAR) Spring Meeting

**2024**

-   Eastern North American Region (ENAR) Spring Meeting
-   Duke Industry Statistics Symposium (DISS)
-   Duke Research Data Visualization Competition and Showcase

**2023**

-   New Directions in Analyzing Text as Data (TADA) Conference *(Recipient of the TADA Travel Award)*
-   Duke Health Data Science Poster Showcase

**2021 – 2022**

-   Electronic Undergraduate Statistics Research Conference (eUSR) (2022)
-   Northfield Undergraduate Mathematics Symposium (NUMS) (2021)
-   Carleton Undergraduate Research and Internship Symposium (2021)

## Published Software

-   **PDA: Privacy-Preserving Distributed Algorithms** (2025). R Package. Co-developed with Luo, C., Duan, R., Tong, J., & Chen, Y. [Available on CRAN](https://cran.r-project.org/web/packages/pda/index.html)
-   **Model of Wheeler** (2022). NetLogo Modeling Commons. Northwestern University Center for Connected Learning and Computer-Based Modeling, Evanston. [Available Here](https://modelingcommons.org/account/models/5618)
